begin;

set local lock_timeout = '5s';

do $$
begin
  if to_regclass('public.whatsapp_gateway_settings') is null then
    raise exception 'Aplique primeiro create_whatsapp_central_stage1_2026-09-14.sql';
  end if;
  if to_regprocedure('public.is_admin()') is null then
    raise exception 'public.is_admin() nao existe';
  end if;
end;
$$;

create table if not exists public.whatsapp_gateway_templates (
  event_type text primary key,
  label text not null,
  body_template text not null,
  allowed_placeholders text[] not null default array[]::text[],
  is_enabled boolean not null default true,
  last_updated_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint whatsapp_gateway_templates_event_type
    check (event_type ~ '^[a-z][a-z0-9_]{2,79}$'),
  constraint whatsapp_gateway_templates_label
    check (char_length(trim(label)) between 3 and 120),
  constraint whatsapp_gateway_templates_body
    check (char_length(trim(body_template)) between 3 and 1600)
);

create table if not exists public.whatsapp_gateway_jobs (
  id uuid primary key default gen_random_uuid(),
  idempotency_key uuid not null default gen_random_uuid(),
  idempotency_contract_version text not null default 'persisted-key-2026-09-21'
    check (idempotency_contract_version in ('legacy-job-id-2026-09-21', 'persisted-key-2026-09-21')),
  event_type text not null references public.whatsapp_gateway_templates(event_type),
  event_key text not null,
  event_cycle bigint,
  source_table text not null,
  source_id uuid,
  recipient_kind text not null default 'admin_default'
    check (recipient_kind in ('admin_default', 'user')),
  recipient_user_id uuid references public.users(id) on delete set null,
  message_body text not null,
  link_path text,
  metadata jsonb not null default '{}'::jsonb,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'retry', 'sent', 'dead_letter', 'skipped')),
  attempts integer not null default 0 check (attempts between 0 and 20),
  max_attempts integer not null default 5 check (max_attempts between 1 and 10),
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  locked_by uuid,
  last_attempt_at timestamptz,
  last_http_status integer,
  last_error_code text,
  provider_message_id text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint whatsapp_gateway_jobs_event_key
    check (char_length(trim(event_key)) between 3 and 300),
  constraint whatsapp_gateway_jobs_event_cycle
    check (event_cycle is null or event_cycle > 0),
  constraint whatsapp_gateway_jobs_source_table
    check (source_table ~ '^[a-z][a-z0-9_]{2,79}$'),
  constraint whatsapp_gateway_jobs_message
    check (char_length(trim(message_body)) between 1 and 1800),
  constraint whatsapp_gateway_jobs_link
    check (link_path is null or link_path ~ '^/(admin|minha-conta)/[A-Za-z0-9/_-]*$'),
  constraint whatsapp_gateway_jobs_metadata_object
    check (jsonb_typeof(metadata) = 'object' and octet_length(metadata::text) <= 4096),
  constraint whatsapp_gateway_jobs_http_status
    check (last_http_status is null or last_http_status between 100 and 599),
  constraint whatsapp_gateway_jobs_error_code
    check (last_error_code is null or char_length(last_error_code) <= 160),
  constraint whatsapp_gateway_jobs_provider_id
    check (provider_message_id is null or char_length(provider_message_id) <= 255)
);

create table if not exists public.whatsapp_announcement_moderation_state (
  announcement_id uuid primary key references public.announcements(id) on delete cascade,
  moderation_cycle bigint not null default 0 check (moderation_cycle >= 0),
  in_moderation boolean not null default false,
  last_entered_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.whatsapp_gateway_enqueue_failures (
  id bigint generated by default as identity primary key,
  event_type text not null,
  source_table text not null,
  source_id uuid,
  error_code text not null,
  occurred_at timestamptz not null default now(),
  constraint whatsapp_gateway_enqueue_failures_event_type
    check (event_type ~ '^[a-z][a-z0-9_]{2,79}$'),
  constraint whatsapp_gateway_enqueue_failures_source_table
    check (source_table ~ '^[a-z][a-z0-9_]{2,79}$'),
  constraint whatsapp_gateway_enqueue_failures_error_code
    check (char_length(error_code) between 1 and 80)
);

alter table public.whatsapp_gateway_templates
  add column if not exists allowed_placeholders text[] not null default array[]::text[];

create unique index if not exists idx_whatsapp_gateway_jobs_event_unique
  on public.whatsapp_gateway_jobs (event_type, event_key);
create unique index if not exists idx_whatsapp_gateway_jobs_idempotency_key
  on public.whatsapp_gateway_jobs (idempotency_key);
create unique index if not exists idx_whatsapp_gateway_jobs_moderation_cycle_unique
  on public.whatsapp_gateway_jobs (
    event_type,
    source_id,
    event_cycle,
    recipient_kind,
    coalesce(recipient_user_id, '00000000-0000-0000-0000-000000000000'::uuid)
  )
  where event_type = 'admin_announcement_pending' and event_cycle is not null;
create index if not exists idx_whatsapp_gateway_jobs_claim
  on public.whatsapp_gateway_jobs (available_at, created_at)
  where status in ('pending', 'retry');
create index if not exists idx_whatsapp_gateway_jobs_stale_processing
  on public.whatsapp_gateway_jobs (locked_at)
  where status = 'processing';
create index if not exists idx_whatsapp_gateway_jobs_recent
  on public.whatsapp_gateway_jobs (created_at desc);
create index if not exists idx_whatsapp_gateway_enqueue_failures_recent
  on public.whatsapp_gateway_enqueue_failures (occurred_at desc);

comment on table public.whatsapp_gateway_templates is
  'Catalogo de templates da Central WhatsApp. Nao contem credenciais.';
comment on table public.whatsapp_gateway_jobs is
  'Fila duravel e idempotente da Central WhatsApp. Telefone e segredo sao resolvidos pelo worker.';
comment on table public.whatsapp_gateway_enqueue_failures is
  'Diagnostico sanitizado de falhas antes da criacao de um job WhatsApp.';

insert into public.whatsapp_gateway_templates (
  event_type, label, body_template, allowed_placeholders, is_enabled
)
values
  ('admin_announcement_pending', 'Anuncio aguardando moderacao', E'*Novo anuncio aguardando moderacao*\n{{title}}', array['title'], true),
  ('admin_edit_request_pending', 'Edicao aguardando aprovacao', E'*Edicao de anuncio aguardando aprovacao*\n{{title}}', array['title'], true),
  ('admin_announcement_reported', 'Anuncio denunciado', E'*Anuncio denunciado exige validacao*\n{{title}}', array['title'], true),
  ('admin_support_message', 'Nova mensagem de suporte', E'*Nova mensagem no suporte*\nTicket: {{subject}}\nEnviado por: {{sender}}\nPrioridade: {{priority}}', array['subject', 'sender', 'priority'], true),
  ('admin_store_campaign_pending', 'Campanha aguardando revisao', E'*Campanha de Loja Parceira aguardando revisao*\n{{title}}', array['title'], true)
on conflict (event_type) do nothing;

update public.whatsapp_gateway_templates
set allowed_placeholders = case event_type
  when 'admin_announcement_pending' then array['title']
  when 'admin_edit_request_pending' then array['title']
  when 'admin_announcement_reported' then array['title']
  when 'admin_support_message' then array['subject', 'sender', 'priority']
  when 'admin_store_campaign_pending' then array['title']
  else allowed_placeholders
end
where event_type in (
  'admin_announcement_pending',
  'admin_edit_request_pending',
  'admin_announcement_reported',
  'admin_support_message',
  'admin_store_campaign_pending'
);

create or replace function public.touch_whatsapp_gateway_queue_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trigger_touch_whatsapp_gateway_templates on public.whatsapp_gateway_templates;
create trigger trigger_touch_whatsapp_gateway_templates
before update on public.whatsapp_gateway_templates
for each row execute function public.touch_whatsapp_gateway_queue_updated_at();

drop trigger if exists trigger_touch_whatsapp_gateway_jobs on public.whatsapp_gateway_jobs;
create trigger trigger_touch_whatsapp_gateway_jobs
before update on public.whatsapp_gateway_jobs
for each row execute function public.touch_whatsapp_gateway_queue_updated_at();

create or replace function public.prepare_whatsapp_gateway_job_contract()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_cycle bigint;
  v_chat_id uuid;
  v_image_url text;
begin
  new.idempotency_key := coalesce(new.idempotency_key, gen_random_uuid());

  if new.event_type = 'admin_announcement_pending' and new.source_id is not null then
    select state.moderation_cycle into v_cycle
    from public.whatsapp_announcement_moderation_state state
    where state.announcement_id = new.source_id;
    v_cycle := greatest(coalesce(v_cycle, 1), 1);
    new.event_cycle := v_cycle;
    new.event_key := new.source_id::text || ':moderation:' || v_cycle::text || ':'
      || new.recipient_kind || ':' || coalesce(new.recipient_user_id::text, 'default');
    new.metadata := coalesce(new.metadata, '{}'::jsonb)
      || jsonb_build_object('moderation_cycle', v_cycle);
  elsif new.event_type = 'seller_new_lead' and new.source_id is not null then
    select leads.chat_id, nullif(trim(announcements.images[1]), '')
    into v_chat_id, v_image_url
    from public.leads leads
    join public.announcements announcements on announcements.id = leads.announcement_id
    where leads.id = new.source_id;

    if v_image_url !~* '^https://dockpbyzrvgewgdoaibn\.supabase\.co/storage/v1/object/public/ads-images/.+\.(jpe?g|png|webp)$' then
      v_image_url := null;
    end if;
    new.metadata := coalesce(new.metadata, '{}'::jsonb)
      || jsonb_strip_nulls(jsonb_build_object(
        'image_url', v_image_url,
        'action_url', case when v_chat_id is not null
          then 'https://agrobw.com.br/minha-conta/mensagens?chat=' || v_chat_id::text
          else null
        end,
        'gateway_contract_version', '2026-09-18',
        'message_type', 'transactional_card'
      ));
  end if;
  return new;
end;
$$;

drop trigger if exists trg_prepare_whatsapp_gateway_job_contract on public.whatsapp_gateway_jobs;
create trigger trg_prepare_whatsapp_gateway_job_contract
before insert on public.whatsapp_gateway_jobs
for each row execute function public.prepare_whatsapp_gateway_job_contract();

alter table public.whatsapp_gateway_templates enable row level security;
alter table public.whatsapp_gateway_templates force row level security;
alter table public.whatsapp_gateway_jobs enable row level security;
alter table public.whatsapp_gateway_jobs force row level security;
alter table public.whatsapp_announcement_moderation_state enable row level security;
alter table public.whatsapp_announcement_moderation_state force row level security;
alter table public.whatsapp_gateway_enqueue_failures enable row level security;
alter table public.whatsapp_gateway_enqueue_failures force row level security;

revoke all on table public.whatsapp_gateway_templates from public, anon, authenticated;
revoke all on table public.whatsapp_gateway_jobs from public, anon, authenticated;
revoke all on table public.whatsapp_announcement_moderation_state from public, anon, authenticated;
revoke all on table public.whatsapp_gateway_enqueue_failures from public, anon, authenticated;
revoke all on sequence public.whatsapp_gateway_enqueue_failures_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.whatsapp_gateway_templates to service_role;
grant select, insert, update, delete on table public.whatsapp_gateway_jobs to service_role;
grant select, insert, update, delete on table public.whatsapp_announcement_moderation_state to service_role;
grant select, delete on table public.whatsapp_gateway_enqueue_failures to service_role;

create or replace function public.render_whatsapp_gateway_template(
  p_template text,
  p_payload jsonb
)
returns text
language plpgsql
immutable
security invoker
set search_path = pg_catalog, pg_temp
as $$
declare
  v_result text := p_template;
  v_key text;
  v_value text;
begin
  if jsonb_typeof(coalesce(p_payload, '{}'::jsonb)) <> 'object' then
    raise exception 'Payload de template invalido' using errcode = '22023';
  end if;

  for v_key, v_value in
    select key, value from jsonb_each_text(coalesce(p_payload, '{}'::jsonb))
  loop
    if v_key ~ '^[a-z][a-z0-9_]{0,49}$' then
      v_result := replace(v_result, '{{' || v_key || '}}', left(coalesce(v_value, ''), 300));
    end if;
  end loop;

  v_result := regexp_replace(v_result, '\{\{[a-z][a-z0-9_]{0,49}\}\}', '', 'g');
  return left(trim(v_result), 1800);
end;
$$;

create or replace function public.enqueue_whatsapp_gateway_event(
  p_event_type text,
  p_event_key text,
  p_source_table text,
  p_source_id uuid,
  p_payload jsonb default '{}'::jsonb,
  p_link_path text default null,
  p_recipient_kind text default 'admin_default',
  p_recipient_user_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_template public.whatsapp_gateway_templates%rowtype;
  v_job_id uuid;
  v_message text;
begin
  if p_event_type like 'marketing_%' then
    raise exception 'Eventos de marketing WhatsApp exigem consentimento especifico'
      using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.whatsapp_gateway_settings settings
    where settings.id = '00000000-0000-0000-0000-000000000020'
      and settings.is_enabled
      and settings.base_url is not null
      and nullif(trim(settings.auth_secret), '') is not null
      and (
        (p_recipient_kind = 'admin_default' and settings.default_recipient_phone is not null)
        or p_recipient_kind = 'user'
      )
  ) then
    return null;
  end if;

  select * into v_template
  from public.whatsapp_gateway_templates templates
  where templates.event_type = p_event_type
    and templates.is_enabled;

  if not found then
    return null;
  end if;
  if p_event_key is null or char_length(trim(p_event_key)) not between 3 and 300 then
    raise exception 'Chave de evento invalida' using errcode = '22023';
  end if;
  if p_source_table is null or p_source_table !~ '^[a-z][a-z0-9_]{2,79}$' then
    raise exception 'Tabela de origem invalida' using errcode = '22023';
  end if;
  if p_link_path is not null and p_link_path !~ '^/(admin|minha-conta)/[A-Za-z0-9/_-]*$' then
    raise exception 'Link administrativo invalido' using errcode = '22023';
  end if;
  if p_recipient_kind not in ('admin_default', 'user') then
    raise exception 'Tipo de destinatario invalido' using errcode = '22023';
  end if;
  if p_recipient_kind = 'user' and p_recipient_user_id is null then
    raise exception 'Usuario destinatario obrigatorio' using errcode = '22023';
  end if;
  if jsonb_typeof(coalesce(p_payload, '{}'::jsonb)) <> 'object'
    or octet_length(coalesce(p_payload, '{}'::jsonb)::text) > 4096 then
    raise exception 'Payload de evento invalido' using errcode = '22023';
  end if;

  v_message := public.render_whatsapp_gateway_template(v_template.body_template, p_payload);
  if nullif(trim(v_message), '') is null then
    raise exception 'Template resultou em mensagem vazia' using errcode = '22023';
  end if;

  insert into public.whatsapp_gateway_jobs (
    idempotency_key,
    event_type,
    event_key,
    event_cycle,
    source_table,
    source_id,
    recipient_kind,
    recipient_user_id,
    message_body,
    link_path,
    metadata
  ) values (
    gen_random_uuid(),
    p_event_type,
    trim(p_event_key),
    case
      when p_event_type = 'admin_announcement_pending'
        then nullif(p_payload->>'moderation_cycle', '')::bigint
      else null
    end,
    p_source_table,
    p_source_id,
    p_recipient_kind,
    p_recipient_user_id,
    v_message,
    p_link_path,
    coalesce(p_payload, '{}'::jsonb)
  )
  on conflict (event_type, event_key) do nothing
  returning id into v_job_id;

  return v_job_id;
end;
$$;

create or replace function public.try_enqueue_whatsapp_gateway_event(
  p_event_type text,
  p_event_key text,
  p_source_table text,
  p_source_id uuid,
  p_payload jsonb default '{}'::jsonb,
  p_link_path text default null,
  p_recipient_kind text default 'admin_default',
  p_recipient_user_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_error_code text;
begin
  return public.enqueue_whatsapp_gateway_event(
    p_event_type,
    p_event_key,
    p_source_table,
    p_source_id,
    p_payload,
    p_link_path,
    p_recipient_kind,
    p_recipient_user_id
  );
exception when others then
  v_error_code := sqlstate;
  begin
    insert into public.whatsapp_gateway_enqueue_failures (
      event_type, source_table, source_id, error_code
    ) values (
      left(coalesce(nullif(trim(p_event_type), ''), 'unknown_event'), 80),
      left(coalesce(nullif(trim(p_source_table), ''), 'unknown_source'), 80),
      p_source_id,
      left(v_error_code, 80)
    );
  exception when others then
    null;
  end;
  raise warning 'Falha isolada ao enfileirar evento WhatsApp %: %', p_event_type, v_error_code;
  return null;
end;
$$;

create or replace function public.claim_whatsapp_gateway_jobs(
  p_limit integer,
  p_worker_id uuid
)
returns setof public.whatsapp_gateway_jobs
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Unauthorized' using errcode = '42501';
  end if;
  if p_worker_id is null then
    raise exception 'Worker obrigatorio' using errcode = '22023';
  end if;

  update public.whatsapp_gateway_jobs jobs
  set
    status = 'dead_letter',
    last_error_code = 'LEASE_EXPIRED',
    locked_at = null,
    locked_by = null
  where jobs.status = 'processing'
    and jobs.locked_at < now() - interval '10 minutes'
    and jobs.attempts >= jobs.max_attempts;

  update public.whatsapp_gateway_jobs jobs
  set
    status = 'skipped',
    last_error_code = 'ADMIN_EVENT_EXPIRED',
    locked_at = null,
    locked_by = null
  where jobs.event_type like 'admin_%'
    and (
      jobs.status in ('pending', 'retry')
      or (jobs.status = 'processing' and jobs.locked_at < now() - interval '10 minutes')
    )
    and jobs.created_at < now() - interval '24 hours';

  return query
  with candidates as (
    select jobs.id
    from public.whatsapp_gateway_jobs jobs
    where (
      (jobs.status in ('pending', 'retry') and jobs.available_at <= now())
      or (jobs.status = 'processing' and jobs.locked_at < now() - interval '10 minutes')
    )
      and jobs.attempts < jobs.max_attempts
    order by jobs.available_at, jobs.created_at
    for update skip locked
    limit least(greatest(coalesce(p_limit, 25), 1), 100)
  )
  update public.whatsapp_gateway_jobs jobs
  set
    status = 'processing',
    attempts = jobs.attempts + 1,
    locked_at = now(),
    locked_by = p_worker_id,
    last_attempt_at = now(),
    last_error_code = null
  from candidates
  where jobs.id = candidates.id
  returning jobs.*;
end;
$$;

create or replace function public.release_whatsapp_gateway_jobs(
  p_worker_id uuid,
  p_job_ids uuid[]
)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_released integer;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Unauthorized' using errcode = '42501';
  end if;
  if p_worker_id is null or coalesce(cardinality(p_job_ids), 0) = 0 then
    return 0;
  end if;

  update public.whatsapp_gateway_jobs jobs
  set
    status = case when jobs.attempts <= 1 then 'pending' else 'retry' end,
    attempts = greatest(jobs.attempts - 1, 0),
    available_at = now(),
    locked_at = null,
    locked_by = null,
    last_attempt_at = null
  where jobs.id = any(p_job_ids)
    and jobs.status = 'processing'
    and jobs.locked_by = p_worker_id;

  get diagnostics v_released = row_count;
  return v_released;
end;
$$;

create or replace function public.complete_whatsapp_gateway_job(
  p_job_id uuid,
  p_worker_id uuid,
  p_http_status integer,
  p_provider_message_id text default null
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Unauthorized' using errcode = '42501';
  end if;

  update public.whatsapp_gateway_jobs jobs
  set
    status = 'sent',
    sent_at = now(),
    last_http_status = p_http_status,
    provider_message_id = nullif(left(trim(coalesce(p_provider_message_id, '')), 255), ''),
    last_error_code = null,
    locked_at = null,
    locked_by = null
  where jobs.id = p_job_id
    and jobs.status = 'processing'
    and jobs.locked_by = p_worker_id;

  return found;
end;
$$;

create or replace function public.fail_whatsapp_gateway_job(
  p_job_id uuid,
  p_worker_id uuid,
  p_error_code text,
  p_http_status integer default null,
  p_retryable boolean default true
)
returns text
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_job public.whatsapp_gateway_jobs%rowtype;
  v_next_status text;
  v_delay_seconds integer;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'Unauthorized' using errcode = '42501';
  end if;

  select * into v_job
  from public.whatsapp_gateway_jobs jobs
  where jobs.id = p_job_id
    and jobs.status = 'processing'
    and jobs.locked_by = p_worker_id
  for update;

  if not found then
    return null;
  end if;

  v_next_status := case
    when coalesce(p_retryable, true) and v_job.attempts < v_job.max_attempts then 'retry'
    else 'dead_letter'
  end;
  v_delay_seconds := least(
    3600,
    (30 * power(2, greatest(v_job.attempts - 1, 0)))::integer
  );

  update public.whatsapp_gateway_jobs jobs
  set
    status = v_next_status,
    available_at = case when v_next_status = 'retry'
      then now() + make_interval(secs => v_delay_seconds)
      else jobs.available_at
    end,
    last_http_status = p_http_status,
    last_error_code = left(coalesce(nullif(trim(p_error_code), ''), 'UNKNOWN_ERROR'), 160),
    locked_at = null,
    locked_by = null
  where jobs.id = v_job.id;

  return v_next_status;
end;
$$;

drop function if exists public.update_whatsapp_gateway_template_admin_safe(text, text, boolean);
drop function if exists public.get_whatsapp_gateway_templates_admin_safe();
create or replace function public.get_whatsapp_gateway_templates_admin_safe()
returns table (
  event_type text,
  label text,
  body_template text,
  allowed_placeholders text[],
  is_enabled boolean,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Unauthorized' using errcode = '42501';
  end if;

  return query
  select templates.event_type, templates.label, templates.body_template,
    templates.allowed_placeholders,
    templates.is_enabled, templates.updated_at
  from public.whatsapp_gateway_templates templates
  order by templates.label;
end;
$$;

create or replace function public.update_whatsapp_gateway_template_admin_safe(
  p_event_type text,
  p_body_template text,
  p_is_enabled boolean
)
returns table (
  event_type text,
  label text,
  body_template text,
  allowed_placeholders text[],
  is_enabled boolean,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_allowed text[];
  v_unknown text[];
  v_probe_payload jsonb;
  v_without_valid_placeholders text;
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Unauthorized' using errcode = '42501';
  end if;
  if nullif(trim(coalesce(p_body_template, '')), '') is null
    or char_length(trim(p_body_template)) > 1600 then
    raise exception 'Template invalido' using errcode = '22023';
  end if;
  if p_event_type = 'marketing_announcement_campaign' and coalesce(p_is_enabled, false) then
    raise exception 'Campanhas de WhatsApp exigem opt-in especifico antes da ativacao' using errcode = '42501';
  end if;

  select templates.allowed_placeholders into v_allowed
  from public.whatsapp_gateway_templates templates
  where templates.event_type = p_event_type;
  if not found then
    raise exception 'Tipo de evento desconhecido' using errcode = '22023';
  end if;

  select array_agg(distinct matches.placeholder_match[1]) into v_unknown
  from regexp_matches(
    p_body_template,
    '\{\{([a-z][a-z0-9_]{0,49})\}\}',
    'g'
  ) as matches(placeholder_match)
  where not (matches.placeholder_match[1] = any(v_allowed));
  if cardinality(coalesce(v_unknown, array[]::text[])) > 0 then
    raise exception 'Placeholder nao permitido: %', array_to_string(v_unknown, ', ')
      using errcode = '22023';
  end if;

  v_without_valid_placeholders := regexp_replace(
    p_body_template,
    '\{\{[a-z][a-z0-9_]{0,49}\}\}',
    '',
    'g'
  );
  if position('{{' in v_without_valid_placeholders) > 0
    or position('}}' in v_without_valid_placeholders) > 0 then
    raise exception 'Sintaxe de placeholder invalida' using errcode = '22023';
  end if;

  select coalesce(jsonb_object_agg(keys.placeholder, 'exemplo'), '{}'::jsonb)
  into v_probe_payload
  from unnest(v_allowed) as keys(placeholder);
  if nullif(trim(public.render_whatsapp_gateway_template(p_body_template, v_probe_payload)), '') is null then
    raise exception 'Template resultaria em mensagem vazia' using errcode = '22023';
  end if;

  update public.whatsapp_gateway_templates templates
  set
    body_template = trim(p_body_template),
    is_enabled = coalesce(p_is_enabled, templates.is_enabled),
    last_updated_by = auth.uid()
  where templates.event_type = p_event_type;

  if not found then
    raise exception 'Tipo de evento desconhecido' using errcode = '22023';
  end if;

  return query
  select templates.event_type, templates.label, templates.body_template,
    templates.allowed_placeholders,
    templates.is_enabled, templates.updated_at
  from public.whatsapp_gateway_templates templates
  where templates.event_type = p_event_type;
end;
$$;

drop function if exists public.get_whatsapp_gateway_queue_summary_admin_safe();
create or replace function public.get_whatsapp_gateway_queue_summary_admin_safe()
returns table (
  pending_count bigint,
  processing_count bigint,
  retry_count bigint,
  sent_today_count bigint,
  dead_letter_count bigint,
  enqueue_failure_count bigint,
  last_queued_at timestamptz,
  last_sent_at timestamptz
)
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
begin
  if auth.uid() is null or not public.is_admin() then
    raise exception 'Unauthorized' using errcode = '42501';
  end if;

  return query
  select
    count(*) filter (where jobs.status = 'pending'),
    count(*) filter (where jobs.status = 'processing'),
    count(*) filter (where jobs.status = 'retry'),
    count(*) filter (
      where jobs.status = 'sent'
        and jobs.sent_at >= (
          date_trunc('day', now() at time zone 'America/Sao_Paulo')
          at time zone 'America/Sao_Paulo'
        )
    ),
    count(*) filter (where jobs.status = 'dead_letter'),
    (
      select count(*)
      from public.whatsapp_gateway_enqueue_failures failures
      where failures.occurred_at >= now() - interval '24 hours'
    ),
    max(jobs.created_at),
    max(jobs.sent_at)
  from public.whatsapp_gateway_jobs jobs;
end;
$$;

create or replace function public.queue_whatsapp_admin_announcement_event()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_new_in_moderation boolean := upper(coalesce(new.status, '')) in ('PENDING', 'UNDER_REVIEW');
  v_old_in_moderation boolean := false;
  v_moderation_cycle bigint;
begin
  if tg_op = 'UPDATE' then
    v_old_in_moderation := upper(coalesce(old.status, '')) in ('PENDING', 'UNDER_REVIEW');
  end if;

  if tg_op = 'INSERT' then
    if new.community_reported_to_review_at is not null then
      perform public.try_enqueue_whatsapp_gateway_event(
        'admin_announcement_reported', new.id::text || ':' || new.community_reported_to_review_at::text,
        'announcements', new.id, jsonb_build_object('title', left(coalesce(nullif(trim(new.title), ''), 'Anuncio'), 300)),
        '/admin/announcement-reports'
      );
    elsif v_new_in_moderation then
      insert into public.whatsapp_announcement_moderation_state as state (
        announcement_id, moderation_cycle, in_moderation, last_entered_at, updated_at
      ) values (
        new.id, 1, true, now(), now()
      )
      on conflict (announcement_id) do update set
        moderation_cycle = case
          when state.in_moderation then state.moderation_cycle
          else state.moderation_cycle + 1
        end,
        in_moderation = true,
        last_entered_at = case when state.in_moderation then state.last_entered_at else now() end,
        updated_at = now()
      returning moderation_cycle into v_moderation_cycle;

      perform public.try_enqueue_whatsapp_gateway_event(
        'admin_announcement_pending',
        new.id::text || ':moderation:' || v_moderation_cycle::text || ':admin_default',
        'announcements', new.id,
        jsonb_build_object(
          'title', left(coalesce(nullif(trim(new.title), ''), 'Anuncio'), 300),
          'moderation_cycle', v_moderation_cycle
        ),
        '/admin/moderation'
      );
    else
      insert into public.whatsapp_announcement_moderation_state (
        announcement_id, moderation_cycle, in_moderation, updated_at
      ) values (new.id, 0, false, now())
      on conflict (announcement_id) do nothing;
    end if;
    return new;
  end if;

  if old.community_reported_to_review_at is null and new.community_reported_to_review_at is not null then
    perform public.try_enqueue_whatsapp_gateway_event(
      'admin_announcement_reported', new.id::text || ':' || new.community_reported_to_review_at::text,
      'announcements', new.id, jsonb_build_object('title', left(coalesce(nullif(trim(new.title), ''), 'Anuncio'), 300)),
      '/admin/announcement-reports'
    );
  elsif v_new_in_moderation
    and not v_old_in_moderation
    and new.community_reported_to_review_at is null then
    insert into public.whatsapp_announcement_moderation_state as state (
      announcement_id, moderation_cycle, in_moderation, last_entered_at, updated_at
    ) values (
      new.id, 1, true, now(), now()
    )
    on conflict (announcement_id) do update set
      moderation_cycle = case
        when state.in_moderation then state.moderation_cycle
        else state.moderation_cycle + 1
      end,
      in_moderation = true,
      last_entered_at = case when state.in_moderation then state.last_entered_at else now() end,
      updated_at = now()
    returning moderation_cycle into v_moderation_cycle;

    perform public.try_enqueue_whatsapp_gateway_event(
      'admin_announcement_pending',
      new.id::text || ':moderation:' || v_moderation_cycle::text || ':admin_default',
      'announcements', new.id,
      jsonb_build_object(
        'title', left(coalesce(nullif(trim(new.title), ''), 'Anuncio'), 300),
        'moderation_cycle', v_moderation_cycle
      ),
      '/admin/moderation'
    );
  end if;

  if v_old_in_moderation and not v_new_in_moderation then
    insert into public.whatsapp_announcement_moderation_state (
      announcement_id, moderation_cycle, in_moderation, updated_at
    ) values (new.id, 0, false, now())
    on conflict (announcement_id) do update set
      in_moderation = false,
      updated_at = now();
  elsif v_new_in_moderation then
    insert into public.whatsapp_announcement_moderation_state (
      announcement_id, moderation_cycle, in_moderation, last_entered_at, updated_at
    ) values (new.id, 1, true, now(), now())
    on conflict (announcement_id) do update set
      in_moderation = true,
      updated_at = now();
  end if;
  return new;
end;
$$;

create or replace function public.queue_whatsapp_admin_edit_request_event()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_title text;
begin
  if new.status <> 'pending' then
    return new;
  end if;
  if tg_op = 'UPDATE' then
    if old.status is not distinct from new.status then
      return new;
    end if;
  end if;

  if new.status = 'pending' then
    select announcements.title into v_title
    from public.announcements announcements
    where announcements.id = new.announcement_id;
    perform public.try_enqueue_whatsapp_gateway_event(
      'admin_edit_request_pending', new.id::text, 'announcement_edit_requests', new.id,
      jsonb_build_object('title', left(coalesce(nullif(trim(v_title), ''), 'Anuncio'), 300)), '/admin/moderation'
    );
  end if;
  return new;
end;
$$;

create or replace function public.queue_whatsapp_admin_support_event()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_ticket public.support_tickets%rowtype;
  v_sender_user_id uuid;
  v_recent_jobs integer;
  v_limit_error_code text;
  v_limit_lock_acquired boolean := false;
  v_limit_lock_attempt integer;
begin
  if new.sender_type <> 'user' then
    return new;
  end if;
  select * into v_ticket from public.support_tickets tickets where tickets.id = new.ticket_id;
  if not found or v_ticket.status not in ('open', 'in_progress', 'waiting_user') then
    return new;
  end if;
  v_sender_user_id := coalesce(new.sender_user_id, v_ticket.user_id);
  begin
    for v_limit_lock_attempt in 1..20 loop
      v_limit_lock_acquired := pg_try_advisory_xact_lock(
        hashtextextended(v_sender_user_id::text, 8675309)
      );
      exit when v_limit_lock_acquired;
      perform pg_sleep(0.01);
    end loop;
    if not v_limit_lock_acquired then
      begin
        insert into public.whatsapp_gateway_enqueue_failures (
          event_type, source_table, source_id, error_code
        ) values (
          'admin_support_rate_limit', 'support_ticket_messages', new.id, 'SUPPORT_RATE_LIMIT_BUSY'
        );
      exception when others then
        null;
      end;
      raise warning 'Limite WhatsApp do suporte ocupado para a mensagem %', new.id;
      return new;
    end if;
    select count(*) into v_recent_jobs
    from public.whatsapp_gateway_jobs jobs
    join public.support_ticket_messages messages on messages.id = jobs.source_id
    where jobs.event_type = 'admin_support_message'
      and messages.sender_user_id = v_sender_user_id
      and jobs.created_at >= now() - interval '10 minutes';
    if v_recent_jobs >= 5 then
      return new;
    end if;
  exception when others then
    v_limit_error_code := sqlstate;
    begin
      insert into public.whatsapp_gateway_enqueue_failures (
        event_type, source_table, source_id, error_code
      ) values (
        'admin_support_rate_limit', 'support_ticket_messages', new.id, left(v_limit_error_code, 80)
      );
    exception when others then
      null;
    end;
    raise warning 'Falha isolada no limite WhatsApp do suporte %: %', new.id, v_limit_error_code;
    return new;
  end;
  perform public.try_enqueue_whatsapp_gateway_event(
    'admin_support_message', new.ticket_id::text || ':' || floor(extract(epoch from now()) / 600)::bigint::text,
    'support_ticket_messages', new.id,
    jsonb_build_object(
      'subject', left(coalesce(nullif(trim(v_ticket.subject), ''), 'Suporte'), 300),
      'sender', left(coalesce(nullif(trim(new.sender_name), ''), 'Usuario'), 120),
      'priority', upper(coalesce(v_ticket.priority, 'medium'))
    ), '/admin/support'
  );
  return new;
end;
$$;

create or replace function public.queue_whatsapp_admin_store_campaign_event()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, pg_temp
as $$
declare
  v_title text;
begin
  if new.status <> 'pending_review' then
    return new;
  end if;
  if tg_op = 'UPDATE' then
    if old.status is not distinct from new.status then
      return new;
    end if;
  end if;

  if new.status = 'pending_review' then
    v_title := coalesce(nullif(new.announcement_snapshot->>'title', ''), 'Campanha de Loja Parceira');
    perform public.try_enqueue_whatsapp_gateway_event(
      'admin_store_campaign_pending', new.id::text, 'seller_store_campaign_requests', new.id,
      jsonb_build_object('title', left(v_title, 300)), '/admin/store-campaigns'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_queue_whatsapp_admin_announcement on public.announcements;
create trigger trg_queue_whatsapp_admin_announcement
after insert or update on public.announcements
for each row execute function public.queue_whatsapp_admin_announcement_event();

drop trigger if exists trg_queue_whatsapp_admin_edit_request on public.announcement_edit_requests;
create trigger trg_queue_whatsapp_admin_edit_request
after insert or update of status on public.announcement_edit_requests
for each row execute function public.queue_whatsapp_admin_edit_request_event();

drop trigger if exists trg_queue_whatsapp_admin_support_message on public.support_ticket_messages;
create trigger trg_queue_whatsapp_admin_support_message
after insert on public.support_ticket_messages
for each row execute function public.queue_whatsapp_admin_support_event();

drop trigger if exists trg_queue_whatsapp_admin_store_campaign on public.seller_store_campaign_requests;
create trigger trg_queue_whatsapp_admin_store_campaign
after insert or update of status on public.seller_store_campaign_requests
for each row execute function public.queue_whatsapp_admin_store_campaign_event();

revoke all on function public.touch_whatsapp_gateway_queue_updated_at() from public, anon, authenticated;
revoke all on function public.prepare_whatsapp_gateway_job_contract() from public, anon, authenticated;
revoke all on function public.render_whatsapp_gateway_template(text, jsonb) from public, anon, authenticated;
revoke all on function public.enqueue_whatsapp_gateway_event(text, text, text, uuid, jsonb, text, text, uuid) from public, anon, authenticated;
revoke all on function public.try_enqueue_whatsapp_gateway_event(text, text, text, uuid, jsonb, text, text, uuid) from public, anon, authenticated;
revoke all on function public.claim_whatsapp_gateway_jobs(integer, uuid) from public, anon, authenticated;
revoke all on function public.release_whatsapp_gateway_jobs(uuid, uuid[]) from public, anon, authenticated;
revoke all on function public.complete_whatsapp_gateway_job(uuid, uuid, integer, text) from public, anon, authenticated;
revoke all on function public.fail_whatsapp_gateway_job(uuid, uuid, text, integer, boolean) from public, anon, authenticated;
revoke all on function public.get_whatsapp_gateway_templates_admin_safe() from public, anon, authenticated;
revoke all on function public.update_whatsapp_gateway_template_admin_safe(text, text, boolean) from public, anon, authenticated;
revoke all on function public.get_whatsapp_gateway_queue_summary_admin_safe() from public, anon, authenticated;
revoke all on function public.queue_whatsapp_admin_announcement_event() from public, anon, authenticated;
revoke all on function public.queue_whatsapp_admin_edit_request_event() from public, anon, authenticated;
revoke all on function public.queue_whatsapp_admin_support_event() from public, anon, authenticated;
revoke all on function public.queue_whatsapp_admin_store_campaign_event() from public, anon, authenticated;

grant execute on function public.enqueue_whatsapp_gateway_event(text, text, text, uuid, jsonb, text, text, uuid) to service_role;
grant execute on function public.claim_whatsapp_gateway_jobs(integer, uuid) to service_role;
grant execute on function public.release_whatsapp_gateway_jobs(uuid, uuid[]) to service_role;
grant execute on function public.complete_whatsapp_gateway_job(uuid, uuid, integer, text) to service_role;
grant execute on function public.fail_whatsapp_gateway_job(uuid, uuid, text, integer, boolean) to service_role;
grant execute on function public.get_whatsapp_gateway_templates_admin_safe() to authenticated;
grant execute on function public.update_whatsapp_gateway_template_admin_safe(text, text, boolean) to authenticated;
grant execute on function public.get_whatsapp_gateway_queue_summary_admin_safe() to authenticated;

commit;
